// All permissions related to application management
const PERMISSIONS = {
  CREATE_APPLICATION: 'create_application',
  VIEW_OWN_APPLICATIONS: 'view_own_applications',
  VIEW_ALL_APPLICATIONS: 'view_all_applications',
  UPLOAD_DOCUMENTS: 'upload_documents',
  VIEW_OWN_DOCUMENTS: 'view_own_documents',
  VIEW_DOCUMENTS: 'view_documents',
  RESUBMIT_APPLICATION: 'resubmit_application',
  REVIEW_APPLICATION: 'review_application',
  REQUEST_ADDITIONAL_DOCUMENTS: 'request_additional_documents',
  MARK_PENDING_APPROVAL: 'mark_pending_approval',
  APPROVE_APPLICATION: 'approve_application',
  REJECT_APPLICATION: 'reject_application',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  VIEW_OWN_AUDIT_SUMMARY: 'view_own_audit_summary',
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles'
};

const DEFAULT_PERMISSIONS = Object.values(PERMISSIONS);

const ROLE_PERMISSION_MAP = {
  superadmin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_ALL_APPLICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  applicant: [
    PERMISSIONS.CREATE_APPLICATION,
    PERMISSIONS.VIEW_OWN_APPLICATIONS,
    PERMISSIONS.UPLOAD_DOCUMENTS,
    PERMISSIONS.RESUBMIT_APPLICATION,
    PERMISSIONS.VIEW_OWN_DOCUMENTS,
    PERMISSIONS.VIEW_OWN_AUDIT_SUMMARY
  ],
  officer: [
    PERMISSIONS.VIEW_ALL_APPLICATIONS,
    PERMISSIONS.REVIEW_APPLICATION,
    PERMISSIONS.REQUEST_ADDITIONAL_DOCUMENTS,
    PERMISSIONS.MARK_PENDING_APPROVAL,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  approver: [
    PERMISSIONS.VIEW_ALL_APPLICATIONS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.APPROVE_APPLICATION,
    PERMISSIONS.REJECT_APPLICATION,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ]
};

// Define permissions that can not be combined for a single role due
const DANGEROUS_PERMISSION_COMBINATIONS = [
  [PERMISSIONS.REVIEW_APPLICATION, PERMISSIONS.APPROVE_APPLICATION],
  [PERMISSIONS.REVIEW_APPLICATION, PERMISSIONS.REJECT_APPLICATION]
];

module.exports = { PERMISSIONS, DEFAULT_PERMISSIONS, ROLE_PERMISSION_MAP, DANGEROUS_PERMISSION_COMBINATIONS };
